spring:
  main:
    banner-mode: off
  application:
    name: shopinventory-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopinventory_app?createDatabaseIfNotExist=true
    username: root
    password: root 
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true